# Generated by Django 5.2.6 on 2025-10-24 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostico', '0001_initial'),
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado'), ('Devuelto', 'Devuelto')], default='Pendiente', max_length=50)),
                ('observaciones', models.CharField(max_length=200)),
                ('diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_entrega', to='diagnostico.estudiante')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporte_entrega', to='recepcion.paciente')),
            ],
        ),
    ]
