# Generated by Django 5.2.6 on 2025-11-28 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
        ('entrega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteentrega',
            name='solucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_soluciones', to='diagnostico.estudiante'),
        ),
    ]
