# Generated by Django 5.2.6 on 2025-11-28 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
        ('entrega', '0002_reporteentrega_solucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteentrega',
            name='diagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_diagnostico', to='diagnostico.estudiante'),
        ),
    ]
