# Generated by Django 5.2.6 on 2025-10-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=50)),
                ('problema', models.CharField(max_length=50)),
            ],
        ),
    ]
