# Generated by Django 5.2.6 on 2025-11-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cliente',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
