# Generated by Django 5.2.6 on 2025-10-24 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=50)),
                ('diagnostico', models.CharField(max_length=50)),
                ('solucion', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], default='Preventivo', max_length=20)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Equipo_diagnosticado', to='recepcion.paciente')),
            ],
        ),
    ]
