# Generated by Django 5.2.6 on 2025-11-28 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_alter_estudiante_equipo'),
        ('recepcion', '0002_alter_paciente_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Equipo_diagnosticado', to='recepcion.paciente'),
        ),
    ]
